/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package mykotlintutorial

import com.amazonaws.regions.AwsRegionProvider
import com.amazonaws.regions.AwsSystemPropertyRegionProvider
import com.amazonaws.regions.DefaultAwsRegionProviderChain
import java.util.*
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

@Configuration
open class SpringAppConfiguration {

    @Bean
    open fun regionProvider(): AwsRegionProvider = DefaultAwsRegionProviderChain()

}

@SpringBootApplication
open class App

fun main(args: Array<String>) {
    val person = Person(1L, "MR", "Vlad", "Ilie", GregorianCalendar(1971,1,1))
    val person2 = Person(2L, "MR", "Vlad", "Ilie")

    println(person)
    println(person2)
    println("If a person is born 2nd Dec 1982 his age is : ${Person.getAge(GregorianCalendar(1982,12,2))}")

    runApplication<App>(*args)
}
